language: node_js
node_js:
 - 6.11.2
before_script:
 - npm install -D
 - npm install -g documentation
script:
 - npm run test
addons:
 ssh_known_hosts: 45.33.27.109
before_install:
- openssl aes-256-cbc -K $encrypted_60adfee9e508_key -iv $encrypted_60adfee9e508_iv
  -in deploy_rsa.enc -out .\\deploy_rsa -d
deploy:
 provider: script
 skip_cleanup: true
 script: cd /home/app/Discoramic9911Website; git pull;
 on:
  branch: master