sudo: required
dist: trusty
language: node_js
node_js:
 - '6.11'
 
before_script:
 - npm install -g @angular/cli
 - npm install
 
notifications:
   slack: technoramic5190:CvjEwxk2fhRNe87HgNn4j4zN

script: ng build
